"""Initial migration

Revision ID: 73eefec39a18
Revises: 
Create Date: 2023-12-27 20:53:33.941122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73eefec39a18'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('journal_ref', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='dwh'
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='staging'
    )
    op.create_table('journal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('journal_ref', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='staging'
    )
    op.create_table('license',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='staging'
    )
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.Column('third_name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='staging'
    )
    op.create_table('sub_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='staging'
    )
    op.create_table('submitter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.Column('third_name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='staging'
    )
    op.create_table('publication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('doi', sa.Text(), nullable=True),
    sa.Column('arxiv_id', sa.Text(), nullable=True),
    sa.Column('update_date', sa.Date(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('submitter_id', sa.Integer(), nullable=True),
    sa.Column('license_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['license_id'], ['staging.license.id'], ),
    sa.ForeignKeyConstraint(['submitter_id'], ['staging.submitter.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='staging'
    )
    op.create_table('authorship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('publication_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['staging.person.id'], ),
    sa.ForeignKeyConstraint(['publication_id'], ['staging.publication.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='staging'
    )
    op.create_table('journal_specifics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journal_id', sa.Integer(), nullable=True),
    sa.Column('publication_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['journal_id'], ['staging.journal.id'], ),
    sa.ForeignKeyConstraint(['publication_id'], ['staging.publication.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='staging'
    )
    op.create_table('publication_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('subcategory_id', sa.Integer(), nullable=True),
    sa.Column('publication_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['staging.category.id'], ),
    sa.ForeignKeyConstraint(['publication_id'], ['staging.publication.id'], ),
    sa.ForeignKeyConstraint(['subcategory_id'], ['staging.sub_category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='staging'
    )
    op.create_table('version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publication_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('create_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['publication_id'], ['staging.publication.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='staging'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('version', schema='staging')
    op.drop_table('publication_category', schema='staging')
    op.drop_table('journal_specifics', schema='staging')
    op.drop_table('authorship', schema='staging')
    op.drop_table('publication', schema='staging')
    op.drop_table('submitter', schema='staging')
    op.drop_table('sub_category', schema='staging')
    op.drop_table('person', schema='staging')
    op.drop_table('license', schema='staging')
    op.drop_table('journal', schema='staging')
    op.drop_table('category', schema='staging')
    op.drop_table('test_table', schema='dwh')
    # ### end Alembic commands ###
