"""Initial Migration

Revision ID: 9bb1b629e0c9
Revises: 
Create Date: 2023-12-30 03:39:07.835301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bb1b629e0c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='dwh'
    )
    op.create_table('journal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('journal_ref', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='dwh'
    )
    op.create_table('license',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='dwh'
    )
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('third_name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='dwh'
    )
    op.create_table('sub_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='dwh'
    )
    op.create_table('publication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.Column('doi', sa.String(length=256), nullable=True),
    sa.Column('arxiv_id', sa.String(length=32), nullable=True),
    sa.Column('update_date', sa.Date(), nullable=True),
    sa.Column('comments', sa.String(length=1024), nullable=True),
    sa.Column('submitter_id', sa.Integer(), nullable=True),
    sa.Column('license_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['license_id'], ['dwh.license.id'], ),
    sa.ForeignKeyConstraint(['submitter_id'], ['dwh.person.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='dwh'
    )
    op.create_table('authorship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('publication_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['dwh.person.id'], ),
    sa.ForeignKeyConstraint(['publication_id'], ['dwh.publication.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='dwh'
    )
    op.create_table('publication_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('subcategory_id', sa.Integer(), nullable=True),
    sa.Column('publication_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['dwh.category.id'], ),
    sa.ForeignKeyConstraint(['publication_id'], ['dwh.publication.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subcategory_id'], ['dwh.sub_category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='dwh'
    )
    op.create_table('publication_journal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journal_id', sa.Integer(), nullable=True),
    sa.Column('publication_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['journal_id'], ['dwh.journal.id'], ),
    sa.ForeignKeyConstraint(['publication_id'], ['dwh.publication.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='dwh'
    )
    op.create_table('version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publication_id', sa.Integer(), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['publication_id'], ['dwh.publication.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='dwh'
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='staging'
    )
    op.create_table('journal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('journal_ref', sa.String(length=256), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='staging'
    )
    op.create_table('license',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='staging'
    )
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('third_name', sa.String(length=128), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='staging'
    )
    op.create_table('sub_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='staging'
    )
    op.create_table('publication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.Column('doi', sa.String(length=256), nullable=True),
    sa.Column('arxiv_id', sa.String(length=32), nullable=True),
    sa.Column('update_date', sa.Date(), nullable=True),
    sa.Column('comments', sa.String(length=1024), nullable=True),
    sa.Column('submitter_id', sa.Integer(), nullable=True),
    sa.Column('license_id', sa.Integer(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['license_id'], ['staging.license.id'], ),
    sa.ForeignKeyConstraint(['submitter_id'], ['staging.person.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='staging'
    )
    op.create_table('authorship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('publication_id', sa.Integer(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['staging.person.id'], ),
    sa.ForeignKeyConstraint(['publication_id'], ['staging.publication.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='staging'
    )
    op.create_table('publication_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('subcategory_id', sa.Integer(), nullable=True),
    sa.Column('publication_id', sa.Integer(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['staging.category.id'], ),
    sa.ForeignKeyConstraint(['publication_id'], ['staging.publication.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subcategory_id'], ['staging.sub_category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='staging'
    )
    op.create_table('publication_journal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journal_id', sa.Integer(), nullable=True),
    sa.Column('publication_id', sa.Integer(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['journal_id'], ['staging.journal.id'], ),
    sa.ForeignKeyConstraint(['publication_id'], ['staging.publication.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='staging'
    )
    op.create_table('version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publication_id', sa.Integer(), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.Date(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['publication_id'], ['staging.publication.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='staging'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('version', schema='staging')
    op.drop_table('publication_journal', schema='staging')
    op.drop_table('publication_category', schema='staging')
    op.drop_table('authorship', schema='staging')
    op.drop_table('publication', schema='staging')
    op.drop_table('sub_category', schema='staging')
    op.drop_table('person', schema='staging')
    op.drop_table('license', schema='staging')
    op.drop_table('journal', schema='staging')
    op.drop_table('category', schema='staging')
    op.drop_table('version', schema='dwh')
    op.drop_table('publication_journal', schema='dwh')
    op.drop_table('publication_category', schema='dwh')
    op.drop_table('authorship', schema='dwh')
    op.drop_table('publication', schema='dwh')
    op.drop_table('sub_category', schema='dwh')
    op.drop_table('person', schema='dwh')
    op.drop_table('license', schema='dwh')
    op.drop_table('journal', schema='dwh')
    op.drop_table('category', schema='dwh')
    # ### end Alembic commands ###
